name       : solid
version    : 5.74.0
release    : 46
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/solid-5.74.0.tar.xz : 70e2356267ed1fdd3a13cd729d91c622aad1ea68a51e1172b0ed9db2468cd4e6
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
