name       : solid
version    : 5.39.0
release    : 8
source     :
    - https://download.kde.org/stable/frameworks/5.39/solid-5.39.0.tar.xz : d98c1bc67a8483d42d76d0369bab3255b30420a5bd41bc4730cabbf03e3c74a5
license    : LGPL-2.1
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
