name       : solid
version    : 5.54.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/solid-5.54.0.tar.xz : 29d70bbed462baac31cce45cf3082600a12ccf53ad1da0a49a3168d72c4cb042
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
