name       : solid
version    : 5.58.0
release    : 31
source     :
    - https://download.kde.org/stable/frameworks/5.58/solid-5.58.0.tar.xz : 7d7f2daaffe8536ee9373375b866c94b949e58f0365990dfe16f9cc05f98bd00
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
