name       : solid
version    : 5.47.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/solid-5.47.0.tar.xz : 5437f3f3a70ff37251d5d88636c39819112c91fcfd36660b6d777d457bdf2e10
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
