name       : solid
version    : 5.77.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/solid-5.77.0.tar.xz : 67d066bcaadffa98960346639e8adacf7a3253fdc10d085d32b9c43fba59d921
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
