name       : solid
version    : 5.52.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/solid-5.52.0.tar.xz : b2f776c595519570f2faa64bb50c5ba6da2c10d078b51bb0608f9d659e8902ca
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
