name       : solid
version    : 5.69.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/solid-5.69.0.tar.xz : 0a033cb7dc0a8040a0e2fa31acfee62251033c98af93a3abe3e45e967a0697b0
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
