name       : solid
version    : 5.56.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/solid-5.56.0.tar.xz : 841d90346cdc51214076cf26357701781d8d534dd209d92768f306e281e46e9e
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
