name       : solid
version    : 5.51.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/solid-5.51.0.tar.xz : 6d05c611277f3e602d03cebb5e5c675faef3abaf03a88e6df0117749c897fa65
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
