name       : solid
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/solid-5.25.0.tar.xz : bd60b642389d5acb0fafb204663ee92a6c44992cb3bb5df7fd34432c32ad04f2
license    : LGPL-2.1
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
