name       : solid
version    : 5.65.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/solid-5.65.0.tar.xz : e94cf8e434b49b8a70318a41219e18b6d2d3b1912a2c3050b69cd66773cc3d00
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
