name       : solid
version    : 5.36.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.36/solid-5.36.0.tar.xz : b10d3d5e1b1f30dd9e283575ab66a4279f0114207b6a69ab1a657403ef03efac
license    : LGPL-2.1
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
