name       : solid
version    : 5.100.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.100/solid-5.100.0.tar.xz : 8d9993ed9d24565cf3a8c9c109ecf900867e5cc13e247fda4faa7118b4244683
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
