name       : solid
version    : 5.82.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.82/solid-5.82.0.tar.xz : e6faad7b72a8e7572fe854e64293bf6b48f566315cc85eaf2dc6baf999332c48
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
