name       : solid
version    : 5.46.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/solid-5.46.0.tar.xz : 358e1d19b6b457e8cf011b520e928390d1c15175f2adc56a3bd31a5d972d9d7b
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
