name       : solid
version    : 5.45.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.45/solid-5.45.0.tar.xz : ade2068f5d0affeff3599ef12b67b016a4518e3085863739f9b6e90685d4b09c
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %patch -p1 < $pkgfiles/Correct-handling-of-removable-file-systems.patch
    %patch -p1 < $pkgfiles/Update-mount-point.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
