name       : solid
version    : 5.109.0
release    : 74
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/solid-5.109.0.tar.xz : bc4dfb6d1792711a48745ddb3698ed764da86fca1f79a1b931072e910b4bd569
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
