name       : solid
version    : 5.50.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/solid-5.50.0.tar.xz : 107ce376baa5c15ee2c218ad35febe7d6e99e9ac35d4b5f184c4618a2e651af9
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
