name       : solid
version    : 5.71.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/solid-5.71.0.tar.xz : 72a7bdd8306ec4cda5f504819e0ff3f8baca6530fa04e33f10b6b89dc010505b
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
