name       : solid
version    : 5.41.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/solid-5.41.0.tar.xz : e327acf724443247a6fe5e51abaf4c11052027996554734ae8e26523f4ed5844
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
