name       : solid
version    : 5.35.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.35/solid-5.35.0.tar.xz : 79f10fcb8b46939e0ae9101b4a3059f849f76e76388b1c946cce848f164c4590
license    : LGPL-2.1
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
