name       : solid
version    : 5.32.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.32/solid-5.32.0.tar.xz : 659310686464d12efd7223f652a82b3401094a57f36ba034e8f16d9577ac1eca
license    : LGPL-2.1
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
