name       : solid
version    : 5.53.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/solid-5.53.0.tar.xz : 964e99e977c0acc6dba42798b57637bd1670b8f5572c9934c7749b50376238f5
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
