name       : solid
version    : 5.55.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/solid-5.55.0.tar.xz : f68a9b56342313d641abc251dbb1cfdeb6a095be7bf9fdb1a864e0405e29bca1
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
