name       : solid
version    : 5.63.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/solid-5.63.0.tar.xz : d4729dca2d6775e897612f8d0f0c5c23335f86aad84270a5b20e8606fd242244
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
