name       : solid
version    : 5.57.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/solid-5.57.0.tar.xz : fbdb0678a5a1b9f902661b4823dbae4629a88708b729d827dd0598799f727209
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
