name       : solid
version    : 5.78.0
release    : 51
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/solid-5.78.0.tar.xz : 129710956e0f9940b00a0b6b9dca86709f3b753ab88debbf93d7ebaeb44bfde1
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
