name       : solid
version    : 5.76.0
release    : 48
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/solid-5.76.0.tar.xz : 7958d047c8bd7622f91541acbe2d554c222218419ee18f395059a09fb90d264d
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
