name       : solid
version    : 5.68.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/solid-5.68.0.tar.xz : 472c1934b3c9cf917f28ac0e5b0864de442b96852744c301d88d8ab7269d74c3
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
