name       : solid
version    : 5.106.0
release    : 72
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.106/solid-5.106.0.tar.xz : 471acaaa850f0ef5116b69caab9293bf3f955dc8a2caedb3f59dd2deacd258af
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
