name       : solid
version    : 5.44.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/solid-5.44.0.tar.xz : 01e3b5c35373abd62f6d6951b8798d5a9f460b68302103832d59665d2a29bc23
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - media-player-info
setup      : |
    %patch -p1 < $pkgfiles/Correct-handling-of-removable-file-systems.patch
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
